CREATE TABLE IF NOT EXISTS users(
     id BINARY(16) PRIMARY KEY,
     email VARCHAR(45) NOT NULL UNIQUE,
     password VARCHAR(100) NOT NULL,
     created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
     modified_at TIMESTAMP WITHOUT TIME ZONE


);